### ISSUE TITLE
Can't Send JSON request to remote HOST because an attribute is encrypted or randomly generated (numeroOrdre)

### ISSUE THREAD

**Issue by 1ntegrxl** [institut-galilee/NASTA#5]
- numeroOrdre seems to be encrypted and generated by backend (no function getnumeroOrdre in invite.js)
![Problem ... ](https://user-images.githubusercontent.com/56651736/69774055-0d59a700-1195-11ea-9c04-fbd3ce030dff.png)

**Comment by HamidiMassinissa** [comment]
What I recall from yesterday's discussions is that you have, first, to get this number (by requesting it from the server), and then use it for you subsequent requests to get the actual information about the planning, at least during the time this number is valid. am I missing something?

**Comment by HamidiMassinissa** [comment]
Pour être dans l'esprit de ce qui vous est demandé, un diagramme de séquence que vous pouvez améliorer:
<p align="center">
<img src="https://user-images.githubusercontent.com/8298445/69806793-0312c980-11e4-11ea-98a9-fa687e68fc61.png"/>
</p>

**Comment by 1ntegrxl** [comment]
I understand that we have to request "numeroOrdre" but I don't see a direct way to do it. If you have a hint or something, it'll be greatly appreciated. I didn't find any XHR that refers to getting this "numeroOrdre" at the beginning of the session.

**Comment by HamidiMassinissa** [comment]
I see. I was assuming that you can get `numeroOrdre` easily and that it is fixed for the entire session. 

What I notice, though, is that `numeroOrdre` changes in a predefined manner, you can check yourself that you have a similar sequence of this number through different sessions. It is an ad-hoc solution but you can probably try to do something with that. One thing remains for you to get, in this case, which is `numeroSession`. What I noticed is that you can get `numeroSession` from the body of the html page:

![screenshot_103](https://user-images.githubusercontent.com/8298445/69833350-81e32300-1233-11ea-8a43-8eb9f2d88e71.png)

![screenshot_102](https://user-images.githubusercontent.com/8298445/69833351-81e32300-1233-11ea-9567-8cf74b503f91.png)

Note that, the most appropriate solution is to use web services if provided. I saw [here](https://www.index-education.com/fr/serviceWebHP.php) a description of web services related to hyperplanning and [here](https://www.index-education.com/fr/hyperplanning-info196-service-web.php) some examples showing how to use use them. You should ask the maintainer of hyperplanning at the university.

The other solution, as we agreed upon, is to rely on the solution provided by @marcjeanpierre which forms a socle for your beta-first-zeroth version and requesting these information information in real-time would be an enhancement.

**Comment by 1ntegrxl** [comment]
I see. Your answer is very clear and complete. @marcjeanpierre 's solution WILL be used and relied on, meanwhile I'll continue searching for a work-around for the previous situation. Thanks for the help, really helpful !

**Comment by HamidiMassinissa** [comment]
[Here](https://repl.it/@riless/hyperplanning) is a link to `nodejs` code and [here](https://repl.it/@riless/hyperplanning-python) is another link to `python` code.
Note that the js code is able to reproduce the url's which is not the case using python.

Many thanks to @riless.

**Comment by 1ntegrxl** [comment]
I took a look into the nodejs code, and it seems to generate "numOrdre" 's correct form, but unfortunately it doesn't seem to be working. When sending a new request with a valid "session ID" and the "numOrdre" generated by @riless 's code, the server times out and returns an error. 
However, I think the most efficient way to do this kind of task is simply to simulate a browser by using headless browsers. I'll be using zombie.js ([http://zombie.js.org/](url)) and I'll try to make it as efficient as possible.
Thanks for the help again @HamidiMassinissa.

**Comment by 1ntegrxl** [comment]
Note that currently, we're STICKING to the method provided by @marcjeanpierre , the method described above would just be an enhancement (as you may have noticed time isn't a thing we have).
